# config for landscape.io: https://landscape.io/github/aisapatino/sjfnw
# also used when running prospector locally

python-targets:
  - 2

ignore-paths:
  - docs
  - libs
  - site
  - scripts

requirements:
  - requirements.txt
  - requirements-lint.txt

uses:
  - django

strictness: none
member-warnings: true
test-warnings: true

mccabe: # complexity checker
  run: false

pyflakes: # static analyzer; mainly covered by pylint
  run: false

pep8:
  disable:
    - E1   # indentation
    - E261 # require two+ spaces before inline comment
    - E302 # require two blank lines
    - E401 # multiple imports per line
    - E501 # line length (checked by pylint)
    - N    # naming (checked by pylint)
