language: python
python:
  - "2.7"

# don't send emails for fixed
notifications:
  email:
    on_success: never
    on_failure: change

install:
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.18.zip
  - unzip -q google_appengine_1.9.18.zip
  - pip install codecov
  # - "pip install pylint"
  # - "pip install pylint-django"

before_script:
  - export PATH=$PATH:$PWD/google_appengine
  - export PYTHONPATH=$PYTHONPATH:$PWD/google_appengine
  - export PYTHONPATH=$PYTHONPATH:$PWD/google_appengine/lib/django-1.5
  - export PYTHONPATH=$PYTHONPATH:$PWD/google_appengine/lib/yaml/lib
  - export PYTHONPATH=$PYTHONPATH:$PWD/google_appengine/lib/webob-1.2.3

# script to run tests
script: ./scripts/coverage.sh skip-html

# send coverage to coveralls if tests passed
after_success: codecov
