# config for https://travis-ci.org/aisapatino/sjfnw

sudo: false
language: python
python:
  - "2.7"

cache:
  - pip: true
  - directories:
    - $HOME/google-cloud-sdk

env:
  global:
    - GAE_PATH=$HOME/google-cloud-sdk/platform/google_appengine
    - PATH=$PATH:${HOME}/google-cloud-sdk/bin:$GAE_PATH
    - PYTHONPATH=$PYTHONPATH:$GAE_PATH:$GAE_PATH/lib/webob-1.2.3:$GAE_PATH/lib/yaml/lib

install:
  - if [ ! -d $HOME/google-cloud-sdk ] || [ ! -d $HOME/google-cloud-sdk/bin ]; then
      rm -rfv $HOME/google-cloud-sdk;
      CLOUDSDK_CORE_DISABLE_PROMPTS=1 curl https://sdk.cloud.google.com | bash;
      gcloud components remove bq gsutil;
    fi
  - if [ ! -d $HOME/google-cloud-sdk/platform/google_appengine ]; then
      gcloud components install app-engine-python;
    fi
  - pip install codecov
  - pip install -r requirements.txt -r requirements-dev.txt

script: ./scripts/coverage skip-html

after_success: codecov

notifications:
  email:
    on_success: never
    on_failure: change
