application: sjf-nw
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- deferred: on

env_variables:
  CLOUDSQL_PASSWORD: 'SJFdb'
  CLOUDSQL_USER: 'root'
  CLOUDSQL_DATABASE: 'sjfdb'

libraries:
- name: "MySQLdb"
  version: "1.2.4"
- name: "webob"
  version: "1.2.3"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*dist-info$
- ^docs$
- ^site$
- ^sjfnw/(.*/)?tests$

handlers:

- url: /_ereporter.*
  script: google.appengine.ext.ereporter.report_generator.application
  login: admin

- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.application
  login: admin

- url: /mail
  script: sjfnw.wsgi.application
  login: admin

- url: /dev
  script: sjfnw.wsgi.application
  login: admin

- url: /static/admin
  static_dir: libs/django/contrib/admin/static/admin
  expiration: '1d'

- url: /static
  static_dir: sjfnw/static
  expiration: '1h'

- url: /favicon\.ico
  static_files: sjfnw/static/favicon.ico
  upload: favicon\.ico
  expiration: '1d'

- url: /.*
  script: sjfnw.wsgi.application
  secure: always
