application: sjf-nw
version: devel
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on
- appstats: on
- deferred: on

libraries:
- name: django
  version: "1.5"

handlers:

- url: /_ereporter.*
  script: google.appengine.ext.ereporter.report_generator.application
  login: admin

- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /mail
  script: sjfnw.wsgi.application
  login: admin

- url: /dev
  script: sjfnw.wsgi.application
  login: admin
  
- url: /static/admin
  static_dir: sjfnw/static/django_admin
  expiration: '0'

- url: /static
  static_dir: sjfnw/static

- url: /favicon\.ico
  static_files: sjfnw/static/favicon.ico
  upload: favicon\.ico

- url: /.*
  script: sjfnw.wsgi.application
