site_name: sjfnw
theme: flatly
include_nav: true
include_next_prev: false
repo_url: https://github.com/aisapatino/sjfnw/
repo_name: sjfnw
theme_dir: 'docs/_theme'
markdown_extensions: [markdown.extensions.nl2br]
google_analytics: ['UA-28076150-3', 'auto']
pages:
- Home: 'index.md'
- Getting started:
  - Installation and setup: 'getting-started/installation-and-setup.md'
  - Running a local server: 'getting-started/local-server.md'
  - Running tests: 'getting-started/running-tests.md'
  - Text editor setup: 'getting-started/text-editor-setup.md'
  - Linters: 'getting-started/linters.md'
- Project info:
  - Overview of models: 'about/models.md'
  - Project structure: 'about/project-structure.md'
  - Code conventions: 'about/code-conventions.md'
  - Documentation: 'about/docs.md'
- Workflow:
  - Git: 'workflow/git.md'
  - Issue tracking: 'workflow/issue-tracking.md'
  - Travis CI & Codecov.io: 'workflow/continuous-integration.md'
  - Deploying: 'workflow/deploying.md'
- Testing:
  - Intro: 'tests/intro-to-testing.md'
  - Writing tests: 'tests/writing-tests.md'
  - Fundraising tests: 'tests/fund.md'
- How to:
  - Performance debugging: 'how-to/debugging-performance.md'
  - Database management: 'how-to/database.md'
  - Support requests: 'how-to/support-requests.md'
- Resources: 'resources.md'
