#!/usr/bin/env bash

pip_version=$(pip --version 2>&1)
if [ $(expr "$pip_version" : '.*not found') -gt 0 ] ; then
  echo "Pip is required to install dependencies. See http://aisapatino.github.io/sjfnw/getting-started/installation-and-setup/"
  exit 1
fi

echo "Installing libs for dev env..."

pip install -r requirements-dev.txt

echo "
Installation complete. To run lint, use the command 'prospector'
"
